use std::sync::Arc;

#[derive(Clone, Debug)]
pub enum StandardControllerButton {
    A,
    B,
    Select,
    Start,
    DPadUp,
    DPadDown,
    DPadLeft,
    DPadRight,
}

#[derive(Clone, Debug)]
pub enum Event {
    ApplyBooleanSetting(String, bool),
    ApplyFloatSetting(String, f64),
    ApplyIntegerSetting(String, i64),
    ApplyStringSetting(String, String),
    CloseWindow,
    CartridgeLoaded(String),
    CartridgeRejected(String, String),
    ChangeDisk(usize, usize),
    GameToggleOverscan,
    GameIncreaseScale,
    GameDecreaseScale,
    LoadCartridge(String, Arc<Vec<u8>>,Arc<Vec<u8>>),
    LoadSram(Arc<Vec<u8>>),
    LoadBios(Arc<Vec<u8>>),
    LoadFailed(String),
    MouseMove(i32, i32),
    MouseClick(i32, i32),
    MouseRelease,
    MemoryViewerNextPage,
    MemoryViewerPreviousPage,
    MemoryViewerNextBus,
    MuteChannel(String, String),
    UnmuteChannel(String, String),
    NesNudgeAlignment,
    NesNewApuHalfFrame,
    NesNewApuQuarterFrame,
    NesNewFrame,
    NesNewScanline,
    NesPauseEmulation,
    NesRenderNTSC(usize),
    NesResumeEmulation,
    NesReset,
    NesRunCycle,
    NesRunFrame,
    NesRunOpcode,
    NesRunScanline,
    NesToggleEmulation,
    RequestFrame,
    RequestCartridgeDialog,
    RequestSramSave(String),
    RequestBios,
    SaveSram(String, Arc<Vec<u8>>),
    ShowApuWindow,
    ShowCpuWindow,
    ShowGameWindow,
    ShowEventWindow,
    ShowMemoryWindow,
    ShowPianoRollWindow,
    ShowPpuWindow,
    ShowTestWindow,
    StandardControllerPress(usize, StandardControllerButton),
    StandardControllerRelease(usize, StandardControllerButton),
    StoreBooleanSetting(String, bool),
    StoreFloatSetting(String, f64),
    StoreIntegerSetting(String, i64),
    StoreStringSetting(String, String),
    ToggleBooleanSetting(String),
    Update,
}
